default_language_version:
    python: python3.10
repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject
          - flake8-builtins
          - pep8-naming
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: mypy
        name: Type checker
        language: python
        types: [python]
        entry: mypy
        args: [--config-file=pyproject.toml]
