services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    networks:
      - babylog
  babylog:
    depends_on:
      - redis
    build:
      context: .
      target: app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    networks:
      - babylog
    volumes:
      - ./src/db:/app/db

networks:
  babylog: