name: Deploy

env:
  ROOT_DIR: "/opt/app/babylog"

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "master" ]
    types: [ "completed" ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event_name != 'pull_request' }}

    steps:

      - uses: actions/checkout@v4

      - name: send files to server
        uses: appleboy/scp-action@v1
        with:
          debug: true
          overwrite: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
          port: ${{ secrets.PORT }}
          source: "src/*,pyproject.toml,poetry.lock,nginx.conf,Dockerfile,docker-compose.yml"
          target: ${{ env.ROOT_DIR }}
          tar_tmp_path: ${{ env.ROOT_DIR }}

      - name: multiple command
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
          port: ${{ secrets.PORT }}
          envs: ROOT_DIR
          script: |
            cd "$ROOT_DIR"
            sudo docker stop babylog-app
            sudo docker compose up --build -d
            sudo service nginx reload
