name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: 'poetry'
      - name: Install poetry packages
        run: poetry install --with dev --no-root
      - name: Set default environment
        run: cp ./.env.ci ./.env
      - name: lint
        run: |
          poetry run mypy src
          poetry run flake8 src
